#Generates a frequency array.
import biolib as bl

Text = "TTGATGGTCAAGTCACTCAGTGGCAAATACAGTATCCATTGTACGGACTTGAGAACTTAACCTGTAGACCTGATCTTTGGTCACGTATACTACGCGACTAAAGCGGCAGGGGTATTACGGTGCGACATTCTTTCCGTCTTTGGAGACCAACTATCCCGACCTGTGACACCGAAGCAATTGTGACTTTAACTAGGAGTCATAAACTTTAGGTGAGCAGGTCAAAGCCGGCTTAGCCTTAGTTACGCCTCAACATTCAGTTGGACGTACTAAACGCCAGTGGTTTTGCCCACGATAAGAACTGAAAGGTTGGATCATATAAACCGTTGATGTCTCCGTTATCTTTAACGTTCACCGTTTACGTTAGGTTTAGCTGGGGGTAATCCTAGCGGCCATTTCTTGAGGATTTCCTGTTTAAGATAGACTGTGCATTCCATAGAATAAATCAGAGAGAGCGCTCTGTGACCCGCCTCAACCCAGCCCTCGCGTTGTGTTAATCCTAATGCACCTTATGTACGCCTTCGCCAAGACTGGAGATTCAACGTGCGAGGTATGCGGTCTTTTAGTTGGTGCAGTTATAACTTAATGGGGAAAGCCCGAACGAGGAGTTCGGCTTTCAGCCGAGTAGCAACTCAGGC"
k = 5

def ComputingFrequencies(Text, k):
    #list to store frequncies
    frequencies = [0]*(4**k)
    
    #iterates through the whole sequence
    for i in range(len(Text) - k + 1):
        #takes current k-mer
        pattern = Text[i:i+k]
        #transfor pattern into index number
        idx = bl.PatternToNumber(pattern)
        #increase frequencie of the current pattern
        frequencies[idx] = frequencies[idx] + 1
    return frequencies
    
freq = ComputingFrequencies(Text,k)
print(freq)


