#Find patterns forming clumps in a string
import biolib as bl

k = 8 #k-mer
L = 24 #clump window
t = 3 #number of times a pattern repeats

#whole genome sequence
genome = "TACGGTACGCGATGCTGATGGCCAGTCATAAAGATGCTGAGTGTAATTTTATCTGAGCAATTATTAGATTAACTCCGCATCGCCCCACAAGCGCCGGGCGGATAGTGCCAGGTGCGAATCGGATCTACATGCAGGCATATCTTTTGCTCGTTTTCAGTTTCGGCGCTGCCAGCCCACGGATAAGAATGGGGAGTCTCAGTGCCGGCGGGTCCGATAAGAATGTCTCCGTGCGTAGACGTTACTGGAGGTACAGCGACTACCTTGGTGCTGGCAGTATACAACTAGAAAGGCGTAGATTACTTTCTTTTTTGATTAGGCCGTGATTTGATTAGGGGTCAGGCACTGCATCATAACCTCCCAGAAATGTGTATTATCTGTAAGTGCGGAGAGGGCAACACTTCCATCTAGAGTGAATTTACTTGTGCCTTCCCAAGGGTGGTGAAATGTCTGCGCTTCGGTTGCAGTATCGGATCTACTCGGTCGGGCTACTAGTGATGTGATAGGATCCGAGGTAAAGGCCAGGAGGTAGGTAAAGAGCTGATTTCCTGTTCACGGATGAGGGGGAGGATGAGGGAGGGATACACATCACACCAGTCGACAGTAGCGAAAAAATTCGCTGACGCTGTCCTCAATCGATCGTCCTCAATCGTCGAGCGCAGGTGGCATAGAGTATCGCTGTCGCGGGTGTTTAGATCGGCATTCTCGGTGAGCCGCACTGATGGACGAGAGCTAGATGAAACCGGGCGGGACGGAATGTCCATAGCAGTTATGTCGGCGCCATTGCGCAGTGTCTTTGTTTACAATGCTTTGCCAGCTACAGTTTACAGCGGCGGAATTCCCATTATTATTATTACGCGTTTATTACGGTAAACGTTGATCAGTAGAGCCCGAAGGGGTCTAGGCAAATACTCGTATACACAAGCTCTAGTATATAACGGGCCAGCATCTAGTGTATCCCGCGCGGATTGGTATAAGCAAGCACCTCCACCTAGCACCTCATGACCGAATTTCGTCATTATCAATGTCTCATGCGAAGGTACGTTGTTTGGCTGGGCTTTGGCCGCCCCTTCCACTTGAGTCTGTTGGTTTAGAGAACTTCTGATCTGACCATACTGGTTAGACCGATCTGCGCTGTCAGGATACCCTCGGAAAACATCCACGCAGGCCTCTTCATCCTTGCCTGTCTCGAAATAATCAATTGTCCGTAGGTTAACCTGACAACTCTAGGTAGGACTAGGAGCGCACGTAGATACGTCGCTAAGCGAGATTGTCTCCACACGTAAATTAATTACACCACACGTAAGGCTATCAAGTCGTGCCCCCATACGCCAAAGAAGTCATACATGAGGTAGCCACGCGTATCATGTGGTTTCCCACCCACAGTCCTACACCGGGGCATTACACCGGCCTTACGCCCGCACTCGCAACAGCTAGGATAACCTGTTATAACCTGTTAACCTGTGCCCAGCACGGACATGTTCGATGGAGGGACGCCGACTTGCGCCTAAACATATTCGATAGACCAGTCCTAAACTTAGCTGGTTCAGTATTCGCATCAGAACCTGAGACCCACCCGAAACAAATCTTCTTCTTATCTTCTTAAATCTGCCGGCCCGCCCAATGCCAATGCCCAATGATCATTGTCTAACCGTCAGAAGGGGCACGTGCCCCTGGGTGTGTGTGTGGTGTGGCAGCATGCACGACACACCTATTGTAACAGGCCTATTAGGGTCGTATGACGACCTTACCTGGACGCCTTTGATACTGTAATGTGGAAATGTGCCTAGCCGGTACATGGCCTGACACGAGCACCAAGTCACCAAGTCACCAAGTCACCAAGTCACCAAGTCACCAAGTCAGCGAGGCGCGAGTCAGAGTCAA"

def ClumpFinding(genome, k, L, t):
    #list to store patterns which form clump
    clumpP = []

    #for loop to slide a window of length L
    for i in range(0, len(genome) - L + 1):
        #find most frequen pattern in i-L window
        freqk = bl.FrequencyMap(genome[i:i+L], k)
        
        #check if the frequent patterns form a clump in a sub-sequence
        for key in freqk:
            #condition to form clump
            if freqk[key] >= t:
                if key not in clumpP:
                    clumpP.append(key)

    return ' '.join(clumpP)

print(ClumpFinding(genome, k, L, t))
    

            
